name: release
on:
  push:
    tags:        
      - 'v*'
permissions:
  contents: read # to fetch the repository content
jobs:
  build-push-monolith:
    uses: docker/github-builder/.github/workflows/build.yml@v1
    permissions:
      id-token: write # to sign attestation(s) with GitHub OIDC Token
      packages: write # to push container image to ghcr
    with:
      output: image
      push: true
      platforms: linux/amd64,linux/arm64
      file: Dockerfile
      sbom: true
      context: .
      set-meta-labels: true
      set-meta-annotations: true
      meta-images: |
        ghcr.io/${{ github.repository_owner }}/backstage
      meta-tags: |
        type=ref,event=tag
        latest
    secrets:
      registry-auths: |
        - registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        - username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PAT }}
        - registry: dhi.io
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PAT }}
  build-push-frontend:
    uses: docker/github-builder/.github/workflows/build.yml@v1
    permissions:
      id-token: write # to sign attestation(s) with GitHub OIDC Token
      packages: write # to push container image to ghcr
    with:
      output: image
      push: true
      platforms: linux/amd64,linux/arm64
      runner: amd64
      setup-qemu: true
      file: Dockerfile.frontend
      sbom: true
      context: .
      set-meta-labels: true
      set-meta-annotations: true
      meta-images: |
        ghcr.io/${{ github.repository_owner }}/backstage-frontend
      meta-tags: |
        type=ref,event=tag
        latest
    secrets:
      registry-auths: |
        - registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
  build-push-backend:
    runs-on: ubuntu-24.04
    permissions:
      id-token: write
      packages: write
    steps:
      - name: checkout code
        uses: actions/checkout@v6
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: docker login ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: docker login docker.io
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PAT }}
      - name: Login to dhi.io
        uses: docker/login-action@v3
        with:
          registry: dhi.io
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PAT }}
      - uses: actions/setup-node@v6
        with:
          node-version: '24'
      - name: remove frontend from backend
        run: |
          export YARN_ENABLE_IMMUTABLE_INSTALLS=false
          make remove-frontend-from-backend
      - name: build and push backend container image
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          file: Dockerfile
          push: true
          provenance: mode=max
          sbom: true
          tags: "ghcr.io/${{ github.repository_owner }}/backstage-backend:${{ github.ref_name }},ghcr.io/${{ github.repository_owner }}/backstage-backend:latest"
  scan:
    runs-on: ubuntu-24.04
    permissions:
      security-events: write
    needs:
      - build-push-monolith
    steps:
      - name: docker login docker.io
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PAT }}
      - name: Login to dhi.io
        uses: docker/login-action@v3
        with:
          registry: dhi.io
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PAT }}
      - name: Docker Scout
        id: docker-scout
        uses: docker/scout-action@v1
        with:
          command: cves
          sarif-file: sarif.output.json
          summary: true
          image: registry://ghcr.io/${{ github.repository_owner }}/backstage:${{ github.ref_name }}
      - name: Upload SARIF report
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: sarif.output.json
