name: release
on:
  push:
    tags:        
      - 'v*'
permissions:
  contents: read # to fetch the repository content
jobs:
  build-push-monolith:
    uses: docker/github-builder/.github/workflows/build.yml@c767551a26459c30e1f683df73a12fdb918f7068 # v1.0.0
    permissions:
      id-token: write # to sign attestation(s) with GitHub OIDC Token
      packages: write # to push container image to ghcr
    with:
      output: image
      push: true
      platforms: linux/amd64,linux/arm64
      runner: amd64
      setup-qemu: true
      file: Dockerfile
      sbom: true
      context: .
      set-meta-labels: true
      set-meta-annotations: true
      meta-images: |
        ghcr.io/${{ github.repository_owner }}/backstage
      meta-tags: |
        type=ref,event=tag
        latest
    secrets:
      registry-auths: |
        - registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        - username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PAT }}
        - registry: dhi.io
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PAT }}
  build-push-frontend:
    uses: docker/github-builder/.github/workflows/build.yml@c767551a26459c30e1f683df73a12fdb918f7068 # v1.0.0
    permissions:
      id-token: write # to sign attestation(s) with GitHub OIDC Token
      packages: write # to push container image to ghcr
    with:
      output: image
      push: true
      platforms: linux/amd64,linux/arm64
      runner: amd64
      setup-qemu: true
      file: Dockerfile.frontend
      sbom: true
      context: .
      set-meta-labels: true
      set-meta-annotations: true
      meta-images: |
        ghcr.io/${{ github.repository_owner }}/backstage-frontend
      meta-tags: |
        type=ref,event=tag
        latest
    secrets:
      registry-auths: |
        - registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
  build-push-backend:
    runs-on: ubuntu-24.04
    permissions:
      id-token: write
      packages: write
    steps:
      - name: checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@c7c53464625b32c7a7e944ae62b3e17d2b600130 # v3.7.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3.12.0
      - name: docker login ghcr.io
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3.7.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: docker login docker.io
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3.7.0
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PAT }}
      - uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
        with:
          node-version: '24'
      - name: remove frontend from backend
        run: |
          export YARN_ENABLE_IMMUTABLE_INSTALLS=false
          make remove-frontend-from-backend
      - name: build and push backend container image
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          file: Dockerfile
          push: true
          provenance: mode=max
          sbom: true
          tags: "ghcr.io/${{ github.repository_owner }}/backstage-backend:${{ github.ref_name }},ghcr.io/${{ github.repository_owner }}/backstage-backend:latest"
  scan:
    runs-on: ubuntu-24.04
    permissions:
      security-events: write
    needs:
      - build-push-monolith
    steps:
      - name: docker login docker.io
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3.7.0
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PAT }}
      - name: Docker Scout
        id: docker-scout
        uses: docker/scout-action@f8c776824083494ab0d56b8105ba2ca85c86e4de # v1.18.2
        with:
          command: cves
          sarif-file: sarif.output.json
          summary: true
          image: registry://ghcr.io/${{ github.repository_owner }}/backstage:${{ github.ref_name }}
      - name: Upload SARIF report
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: sarif.output.json
